name = "Daemon"
uuid = "c3aee05f-4a6b-4834-aae0-ff1a2f3fd2c6"
authors = ["daemon369"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
