name = "Daemon"
uuid = "c3aee05f-4a6b-4834-aae0-ff1a2f3fd2c6"
authors = ["daemon369"]
version = "1.1.4"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
